project:
  type: website
  output-dir: docs

website:
  favicon: images/favicon_transparent.png
  navbar:
    title: false
    logo: images/favicon_transparent.png
    logo-alt: "Logo for Melissa Widas with water droplet and three hexagons"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: blog.qmd
        text: My Work
    right: 
      - text: Get in Touch!
        menu: 
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/mwidas/
            target: _blank
          - icon: envelope
            text: Email
            href: mailto:mel.widas@gmail.com
            target: _blank
          - icon: github
            text: GitHub
            href: https://github.com/mwidas
            target: _blank
          # - icon: envelope-open-text
          #   href: resume.qmd
          #   text: Resume
          #   target: _blank
            
  page-footer: 
    background: dark
    left: 
     - Copyright 2023, Melissa Widas
    right:
     - This website is built with Quarto
format:
  html:
    theme:
      - styles.scss
    css: styles.css
    mainfont: Roboto
    toc: true
    page-layout: full

editor: visual

