project:
  type: website
  output-dir: docs

website:
  title: "Melissa Widas"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    page-layout: full

editor: visual

